spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cook_pro
    username: root
    password:
      initialization-mode: always
  sql:
    init:
      mode: always

doma:
  dialect: ORACLE
  naming: SNAKE_LOWER_CASE