spring:
  datasource:
    url: jdbc:mysql://localhost
    username: root
    password:
      initialization-mode: always
  sql:
    init:
      mode: always

doma:
  dialect: ORACLE
  naming: SNAKE_LOWER_CASE